Remove fail step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -13,10 +13,10 @@ jobs:
   echo-goodbye:
      runs-on: ubuntu-latest
      steps:
-      - name: Failed Step
-        run: | 
-          echo "I will fail"
-          exit 1 
+      # - name: Failed Step
+      #   run: | 
+      #     echo "I will fail"
+      #     exit 1 
       - name: Successful Step
         run: |
           echo "This is successful step"
